site_name: earthcarekit 0.19.0 documentation

repo_url: https://github.com/TROPOS-RSD/earthcarekit

extra_css:
  - stylesheets/extra.css

theme:
  name: "material"
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.image.lightbox
    - toc.follow
  language: en
  font:
    text: Roboto
    code: JetBrains Mono
  logo: https://raw.githubusercontent.com/TROPOS-RSD/earthcarekit-docs-assets/refs/heads/main/assets/images/logos/earthcarekit-icon-white.png
  favicon: https://raw.githubusercontent.com/TROPOS-RSD/earthcarekit-docs-assets/refs/heads/main/assets/images/logos/earthcarekit-favicon-blue.png
  palette:
    # Auto/light/dark mode toggle
    # Automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: fontawesome/solid/circle-half-stroke
        name: Light color mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/sun
        name: Dark color mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: fontawesome/solid/moon
        name: System color mode

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: friendly
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - tables
  - toc:
      permalink: "#"

plugins:
  - autorefs
  - search
  - macros
  - mkdocstrings:
      handlers:
        python:
          options:
            allow_inspection: true
            inherited_members: true
            separate_signature: true
            modernize_annotations: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_root_heading: false
            show_source: true
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            backlinks: false
            show_attribute_values: true
            annotations_path: brief
            line_length: 100
            members_order: alphabetical
            group_by_category: true
            filters:
            - "!^_"
  - glightbox:
      skip_classes:
        - skip-lightbox
  - literate-nav:
      nav_file: SUMMARY.md

nav:
  - Getting started:
    - About: index.md
    - Setup: setup.md
    - Supported products: supported_products.md
  - User guide:
    - Quickstart: tutorials/quickstart.md
    - Colormaps: tutorials/colormaps.md
    - Working with profiles: tutorials/profiles.md
    - Rebin X-MET along-track: tutorials/xmet_rebin_along_track.md
    - Curtain plot customizations: tutorials/plot_customization.md
    - Map plots: tutorials/maps.md
    - CLI tools:
      - Download tool: cli/ecdownload.md
      - Quicklook tool: cli/ecquicklook.md
  - Developer:
    - API reference: api_ref/
    - Release notes: releases/

copyright: |
  <span style="opacity: 0.7;">Copyright &copy; 2025 TROPOS</span>
  </br>
  <span style="opacity: 0.7;">Developed at</span> <a href="https://www.tropos.de/en/">Leibniz Institute for Tropospheric Research</a>
  </br>
  <span style="opacity: 0.7;">Documentation made with</span> <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>

extra:
  version: "0.19.0"
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/TROPOS-RSD/earthcarekit
      name: GitHub
    - icon: simple/zenodo
      link: https://doi.org/10.5281/zenodo.16813294
      name: Zenodo